### ISSUE TITLE
Week 0 Review Ticket - Chris

### ISSUE THREAD

**Issue by Chom642** [AkhilNandhakumar/Guython#10]

**Comment by KoolKidKai** [comment]
Total Score /5

Team Pages /2
- [ ] Web Project: Project Description, Project Plans/Ideas/Wires, Time box

- [ ] Team Roles described, Project Owner or Sponsor described, Scrum Board started

Personal Pages /3
- [ ] GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page

- [ ] GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime

- [ ] GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime
