### ISSUE TITLE
Week 1 Team Review Ticket

### ISSUE THREAD

**Issue by JakubPonulak** [AkhilNandhakumar/Guython#13]
**Team:**
- [Initial Requirements & owner contact info,]()
- tangible plans:
  - [Github Pages plan](https://docs.google.com/drawings/d/1mogokqAFAM5HKk9fLhzz1qdr9THwx2xbRpUxEg_czEs/edit?usp=sharing)
  - [Calendar Notetaker plan](https://docs.google.com/drawings/d/1zjt5Qdw6l88m8sk59pMLM-W7xGrRt5vsgfnX6R5dAaE/edit?usp=sharing)
  - [Overall Planning](https://github.com/AkhilNandhakumar/Guython#project-plans)
- Scrum Board:
<img src="https://github.com/AkhilNandhakumar/Guython/blob/main/static/scrumboardW1.png?raw=true">

**Comment by jm1021** [comment]
CSP students prepare for AP Exam.   SCCS thoughts expanded.  Started incorporating talks.   Thu owner review meeting.   Student calendar.  

1.9/2
