### ISSUE TITLE
Week 1 Indi Ticket - Jakub

### ISSUE THREAD

**Issue by JakubPonulak** [AkhilNandhakumar/Guython#15]
**Total score: 4.85/5 (1.9/2 Team + 2.95/3 Indi)**
**Graded by: Armaan S**
Individual GitHub pages (3 points)
GitHub page for Test Prep study, requiring 5.3, 5.4 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on [cspcoders](https://cspcoders.nighthawkcodingsociety.com/)).
- [x] 1- One Check 5.3
- [x] 1- One Check 5.4

GitHub page that documents key learnings and code snippets using GitHub and replit.

InfoDB lists
- [x] 1 - One Check for New Data, minimum of 4 items

InfoDB loops
- [x] 1- One Check For Loop running and sensible output
- [x] 1- One Check While Loop running and sensible output
- [x] 1- One Check Recursion running and sensible output

Fibonacci - (For Fibonacci(n) print complete list 0 - n and not just the nth term)
- [x] 4- Four checks: Algorithm, code with comments, Prints result, Prints Complete List,
- [x] 1- One check: comments and documentation throughout

**Comment by xXAASXx** [comment]
# Score: 2.95/3
## Total out of 11 = 10.9/11
I like how you added Elon Musk to your Loops, he is a very good person to look up to and I like how organized your individual Github Page is. This makes everything very easy to spot, only thing I can recommend is to do a table for your home page as it will be easier to add to and look nicer.
