### ISSUE TITLE
Week 2 Team Review Ticket

### ISSUE THREAD

**Issue by AkhilNandhakumar** [AkhilNandhakumar/Guython#18]
- [x] **[Big Idea](https://github.com/AkhilNandhakumar/Guython#project-description)**, Sponsor - **Mr. Mortensen**, Hosting Plan - **Temporary AWS hosting for development**, **[GitHub license](https://github.com/AkhilNandhakumar/Guython/blob/main/LICENSE)**
- [x] WireFrames or Web Page Designs:
  - **[Calendar wireframe](https://docs.google.com/presentation/d/1LQfwvtHj-Fy-zm9Yuaey_KsImMZtQ5-ZTAPahqgjO98/edit?usp=sharing)**
  - [Overall Plan](https://github.com/AkhilNandhakumar/Guython#project-plans)
- [x] **[Key Workflow](https://docs.google.com/drawings/d/1mogokqAFAM5HKk9fLhzz1qdr9THwx2xbRpUxEg_czEs/edit?usp=sharing)** or actions within site.
- [x] Data and any Data Privacy **(Picture below for login database to use admin perms to edit calendar and content of site)**

![image](https://user-images.githubusercontent.com/89219514/160197012-c5e6132b-dee9-4f15-b175-7664631754ed.png)

**Comment by jm1021** [comment]
Review ticket is very well organized.  Study website for CSP students.   Multiple features on teaching like CSS, JavaScript, Python.

License is GPL as project is education, they don't want people to take project and sell it.  

Teacher calendar, student calendar.   Actual dates.  

GitHub pages maintaining key content.

Shared wire frame that is starting to show flow of website.   

Discussed Login and allowing people to perform commenting or talking with each other.

Question on  separation: Seems like a better focus is needed on two sites.   Integrating domains.
