### ISSUE TITLE
Week 2 Review Ticket  - Yash S

### ISSUE THREAD

**Issue by YashShah138** [AkhilNandhakumar/Guython#19]
## Graded by Jason O

- [X] [GitHub page](https://yashshah138.github.io/Data_Structures1/) that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of  TT2 for details)
   - [X] [Organize files, directories, and menus](https://replit.com/@YashShah49/DataStructures1#.replit) for the first 3 weeks
   - [X] Write [Factorial function using classes](https://replit.com/@YashShah49/DataStructures1#tt2/classes.py), providing implementation of call.
   - [X] Select your [own Math function](https://replit.com/@YashShah49/DataStructures1#tt2/classes.py). Write it in Imperative and OOP form. 
   - [X] Extra Credit. Write [Palindrome function](https://replit.com/@YashShah49/DataStructures1#tt2/classes.py) using classes, must provide an implementation of call.  Must indicate where the error occurs on front and back comparison.

**Comment by JasonO12** [comment]
4/3 Individual.

- Files are organized by tech talk subjects in replit and python files.
- Factorial successfully implemented with classes.
- Used math function for sequential sums. Both OOP and imperative form work.
- Extra Credit for palindrome works using classes, ignoring special characters and correcting incorrect values. +1
