### ISSUE TITLE
Week 2 Review Ticket - Chris

### ISSUE THREAD

**Issue by Chom642** [AkhilNandhakumar/Guython#21]
Score: 4.4/5
individual:2.5
Team Score:1.9/2
Grader:Ritvik Keerthi

- [x] GitHub page that documents key learnings and code snippets using GitHub and replit (See Challenges at the bottom of  TT2 for details)
   - [x] [Organize files, directories, and menus](https://replit.com/@YashShah49/DataStructures1#.replit) for the first 3 weeks
   - [x] Write [Factorial function using classes](https://replit.com/@YashShah49/DataStructures1#tt2/classes.py), providing implementation of call.
   - [x] Select your [own Math function](https://replit.com/@YashShah49/DataStructures1#tt2/classes.py). Write it in Imperative and OOP form. 
   - [ ] Extra Credit. Write [Palindrome function](https://replit.com/@YashShah49/DataStructures1#tt2/classes.py) using classes, must provide an implementation of call.  Must indicate where the error occurs on front and back comparison.

**Comment by Ritvik-Keerthi** [comment]
Individual Score: 2.5/3

Grader: Ritvik Keerthi

Organize Files, Directories, and Menus --> Pretty organized, different folders for each tech talk program.
[Factorial Function using Classes ](https://replit.com/@Chom642/DataStructures#tt2/classes.py)--> Code is there in the file and neat and organized, however Factorial Function doesn't work and isn't in submenu. Needs to be fixed. (-0.5)
[Math function](https://replit.com/@Chom642/DataStructures#tt2/classes.py) --> Code is there in the file and neat and organized however once again math function doesn't work and isn't in submenu. Needs to be fixed. (-0.5)
[Palindrome function](https://replit.com/@Chom642/DataStructures#tt2/classes.py) --> Code is again there in the file and neat and organized. Given +0.5 for having some code in there that doesn't work in the submenu.
