### ISSUE TITLE
Week 3 Review Ticket - Akhil - Algorithmic Final

### ISSUE THREAD

**Issue by AkhilNandhakumar** [AkhilNandhakumar/Guython#25]
# Total Checks: 9.75/10 by Tanay Rayavarapu
## [Video Link](https://youtu.be/SJqbC-DlWFU)
***
## Quality of Work/Organization
- **[Github Pages](https://akhilnandhakumar.github.io/Akhil-Data-Structures/index)**
- **[Replit](https://replit.com/@AkhilNandhakuma/Akhil-Data-Structures#menu/_menu.py)**
- **Review Tickets (also included on github pages):** [Open Tickets](https://github.com/AkhilNandhakumar/Guython/issues?q=is%3Aissue+is%3Aopen+label%3Aakhil), [Closed Tickets](https://github.com/AkhilNandhakumar/Guython/issues?q=is%3Aissue+label%3Aakhil+is%3Aclosed)
***
## Coding Review/Requirments
- **[GitHub Pages for Tech Talk*](https://akhilnandhakumar.github.io/Akhil-Data-Structures/tt)*
- **[GitHub Commits](https://github.com/AkhilNandhakumar/Akhil-Data-Structures/commits/main)** 
- **[Github Insights](https://github.com/AkhilNandhakumar/Akhil-Data-Structures/pulse)**
- **Code Running on Replit and IntelliJ** (Demonstrated in Video)
- **[Commits in Crossover Repo](https://github.com/TANAY101405/TanayRayavarapu/commits?author=AkhilNandhakumar)** 
***

**Comment by TANAY101405** [comment]
# Total Score: 9.75/10

- [x ] GitHub Pages showing key learnings and challenges conquered from Tech Talks
- [x] GitHub commits you have made, show GitHub insights into your code commits.
- [x] Show Code running on Replit as well as IntelliJ
- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [x] List and Loops: show runtime, code organization, code and comments
- [x] Class review and understanding: show runtime, code organization, code and comments
- [x] Crossover Contributions
- [ ] Python Enhanced learning practice

## Comments/Suggestions:
Your video was very well done and your code/runtime was well explained. However, you were missing any coding practice that showed that you are trying to improve your python ability. As well, I think you could have explored the menu organization a bit further, but it was good with the 2 minute requirement.
