### ISSUE TITLE
Week 3 Review Ticket-Christopher Hom

### ISSUE THREAD

**Issue by Chom642** [AkhilNandhakumar/Guython#27]
Total Score 9.15/10
Grader: Ritvik Keerthi
Github + Crossover
[Individual Github](https://chom642.github.io/Data_Structures/)
[Crossover Github](https://ritvik-keerthi.github.io/Ritvik-Keerthi-CSP4/)
[Individual Replit](https://replit.com/@Chom642/DataStructuresGithubPages#.replit)
[Crossover Replit](https://replit.com/@RitvikKeerthi/Ritvik-Keerthi-CSP4#main.py)

Individual 
[Commits](https://github.com/Ritvik-Keerthi/Ritvik-Keerthi-CSP4/commits?author=Chom642)
[Replit runtime](https://chom642.github.io/Data_Structures/project_doc)
[Video playlist](https://www.youtube.com/watch?v=gMyALVGe7pk&list=PLz6C6Oy0nScnWnOGFjvnkG3G8Wu2B6IKh)

**Comment by Ritvik-Keerthi** [comment]
# INDIVIDUAL SCORE:    /10

Graded By: Ritvik Keerthi

### Quality of work

Share link(s) on slack to final work:  GitHub pages, Replit, Review Ticket(s), TimeBox, or other methods you have used to organize work.

### Coding Review

## Individual Coding:
- [ ] GitHub Pages showing key learnings and challenges conquered from Tech Talks
- [ ] GitHub commits you have made, show GitHub insights into your code commits.
- [ ] Show Code running on Replit as well as IntelliJ
- [ ] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [ ] List and Loops: show runtime, code organization, code and comments
- [ ] Class review and understanding: show runtime, code organization, code and comments

- [ ] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo. Show anything you have done to enhance what you have learned from Python code


### Video 2 minutes: showing the above, quality suggested as follows

- [ ] Make sure you cover everything, but create your own order and optimize time
- [ ] Use Voice or Captions.   Try not to wiggle mouse a lot or over scroll.  Make sure you have a clear plan before you start.
- [ ] Perform video in small parts 15-30 seconds and finish a key subject.  Then put the final Video together with Video editing or Youtube playlists.

**Comment by Chom642** [comment]
INDIVIDUAL SCORE:  9.9/10
Akhil Nandhakumar
ALGORITHMIC FINAL REVIEW TICKET
-------------------------------------------


## Individual Coding:
- [x] GitHub Pages showing key learnings and challenges conquered from Tech Talks
- [x] GitHub commits you have made, show GitHub insights into your code commits.(.9/1) Missing GitHub insights into commits
- [x] Show Code running on Replit as well as IntelliJ
- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments 
- [x] List and Loops: show runtime, code organization, code and comments 
- [x] Class review and understanding: show runtime, code organization, code and comments

- [x] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo. Show anything you have done to enhance what you have learned from Python code


### 2 Minute Video

- [x] Make sure you cover everything, but create your own order and optimize time
- [x] Use Voice or Captions.   Try not to wiggle mouse a lot or over scroll.  Make sure you have a clear plan before you start.
- [x] Perform video in small parts 15-30 seconds and finish a key subject.  Then put the final Video together with Video editing or Youtube playlists.

**Comment by Ritvik-Keerthi** [comment]
Akhil Algorithmic Review Ticket

## Individual Coding:
- [x] GitHub Pages showing key learnings and challenges conquered from Tech Talks
- [x ] GitHub commits you have made, show GitHub insights into your code commits.
- [x] Show Code running on Replit as well as IntelliJ
- [x] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
- [x] List and Loops: show runtime, code organization, code and comments
- [x] Class review and understanding: show runtime, code organization, code and comments

- [x] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo. Show anything you have done to enhance what you have learned from Python code


### Video 2 minutes: showing the above, quality suggested as follows

- [x] Make sure you cover everything, but create your own order and optimize time
- [x] Use Voice or Captions.   Try not to wiggle mouse a lot or over scroll.  Make sure you have a clear plan before you start.
- [x] Perform video in small parts 15-30 seconds and finish a key subject.  Then put the final Video together with Video editing or Youtube playlists.


Akhil has everything required in the video, as it is very compelling and interesting to listen and watch. I think that something he could improve on would be the speed of talking in the vide, as he goes fast a little bit. Therefore, I would give him a 9.8/10.
