### ISSUE TITLE
Week 3 Review Ticket - Yash Shah

### ISSUE THREAD

**Issue by YashShah138** [AkhilNandhakumar/Guython#28]
# Grade: 9/10
# Graded by Colin Howard

### [Replit](https://replit.com/@YashShah49/DataStructures1#.replit)
- [menus](https://replit.com/@YashShah49/DataStructures1#tt0/functions.py)
- [Lists and Loops](https://replit.com/@YashShah49/DataStructures1#tt1/loops.py)
- [Extra Learnings](https://replit.com/@YashShah49/TRIPLET)

### [Github Pages](https://yashshah138.github.io/Data_Structures1/)
- [Timebox](https://yashshah138.github.io/Data_Structures1/)
- [Key Insights](https://yashshah138.github.io/Data_Structures1/project_doc)
- [Personal Commits](https://github.com/YashShah138/Data_Structures1/commits?author=YashShah138)

### Crossover Github
- [Replit](https://replit.com/@ByronLu/AP-CSP-Tri-3-Replit)
- I made the snake game

**Comment by KoolKidKai** [comment]
Final Score /10

### Individual Coding
- [ ] Pages showing key learnings and Tech Talk Challenges

- [ ] Github commits, insights into commits

- [ ] Code running on Replit and IntelliJ

- [ ] Menu Review: lists, navigation, runtime, organization, code, comments

- [ ] Lists and Loops: runtime, organization, code, comments

- [ ] Class Review: runtime, organization, code, comments

- [ ] Crossover Contribution: work done in crossover, replit runtime, commits in repo, anything done to enhance learning


### Video
- [ ] Organized order, optimized time

- [ ] Voice or captions, clear plan, don't wiggle/scroll lots

- [ ] video in small segments then put together

**Comment by KoolKidKai** [comment]
**Akhil's Video Grading /10**

- [ ] Github pages showing key learnigs and tech talk challenges
- [ ] Github commits and insights into code
- [ ] runtime on replit and intelliJ
- [ ] Menu Review: lists and navigation
- [ ] Lists and Loops: runtime, organization, code and comments
- [ ] crossover contributions
- [ ] Enhanced learnign practice
- [ ] small segments put together
- [ ] code/captions, organized/optimized

Final Thoughts:
Its a very nicely done video. It was all taken in one shot it seems, so I think adding a few cuts could help organize it better. There also could've been more focus on enhanced learnings to understand python.

**Comment by jm1021** [comment]
Interesting on Snake and Tic-Tak-Toe.  Most of the rest of the video was more of a tour of menus or CB notes.   It lacked in planning and emphasis as kind of stated above 9/10.

**Comment by jm1021** [comment]
On you GH Pages you have kind of a mix of styles (timbox style and submenus).  Pick one or the other.  Also, you have broken repl embed, try ?lite=true in url.
