### ISSUE TITLE
Week 4 Review Ticket - Jakub

### ISSUE THREAD

**Issue by JakubPonulak** [AkhilNandhakumar/Guython#30]
- CB Create Task: [Documentation & Runtime](https://jakubponulak.github.io/DataStructures/ct_doc)
- Accounts & Logins:
  - [Hack 1](https://github.com/AkhilNandhakumar/Guython/blob/22efa880acf07741a78aadb5c1ce9847e2c49df8/cruddy/templates/cruddy/authorize.html#L34)
  - Hack 2: [Frontend](https://github.com/AkhilNandhakumar/Guython/blob/22efa880acf07741a78aadb5c1ce9847e2c49df8/cruddy/templates/cruddy/crud.html#L28-L30), [Backend](https://github.com/AkhilNandhakumar/Guython/blob/22efa880acf07741a78aadb5c1ce9847e2c49df8/cruddy/query.py#L113-L114)
  - [Hack 3](https://github.com/AkhilNandhakumar/Guython/blob/22efa880acf07741a78aadb5c1ce9847e2c49df8/cruddy/app_crud.py#L126-L130)

**Comment by JasonO12** [comment]
1. CT Documentation: all CB questions for create task are documented on GH pages, and repair embed and video are linked as well. 1/1
2. CT runtime: project runtime on repair works as intended and can be accessed from embed on GH pages. 1/1

**Comment by tangalice** [comment]
total score: 5/5

create task runtime works and requirements all documented in GitHub Pages 2/2

- [ ] hack 1: phone number required for signing up/creating new account
- [ ] hack 2: logout button present on page and works successfully
- [ ] hack 3: login required to be able to access and use search bar feature
3/3
