### ISSUE TITLE
Week 4 Review Ticket -- Yash S

### ISSUE THREAD

**Issue by YashShah138** [AkhilNandhakumar/Guython#33]
## CB Create Task
- [Create Task](https://replit.com/@YashShah49/TRIPLET)

## Login Hacks
- [Hack 1-3 Commits](https://github.com/YashShah138/Guython/commit/b9c12c0ce7b7bad9bc05a89b2881ff5d1c4eb346)

**Comment by dtsivkovski** [comment]
## Total Score: 5/5 - Graded by Daniel Tsivkovski

### Create Task - 2/2
- Written responses are present
- A runtime link is also available that works as intended

### Login Hacks - 3/3
- Hack 1 Add Phone Number to Sign Up screen - Commit present and works as intended
- Hack 2 Add logout to CRUD screen, display logged-in user - Commit present and works as intended
- Hack 3 Add login_required to another portion of project - Commit present and works as intended
