### ISSUE TITLE
Week 5 study plan - Christopher Hom

### ISSUE THREAD

**Issue by Chom642** [AkhilNandhakumar/Guython#38]
-Review Collegeboard videos and big ideas
-Look over tpt notes from tri 1 and 2
-Look over quizlets of terms
-Look over previous quizzes and do more practice quizzes

**Comment by KoolKidKai** [comment]
Score /5

- [ ] Study plan and reflection
 - good plan, could use some reflection on how the progress and preparation is going.
- [ ] Quiz 1
 - 
- [ ] Quiz 2
- [ ] Create task reviewed by another person
- [ ] review ticket and crossover score
