### ISSUE TITLE
Week 5 Review Ticket - Yash Shah

### ISSUE THREAD

**Issue by YashShah138** [AkhilNandhakumar/Guython#41]
[PBL Plan](https://github.com/AkhilNandhakumar/Guython/issues/35)
[Study Plan](https://github.com/AkhilNandhakumar/Guython/issues/37)
[Test Corrections](https://github.com/AkhilNandhakumar/Guython/issues/40)
[Secondary Link for Test Corrections](https://yashshah138.github.io/Data_Structures1/TT)
[Create Task Code and Runtime](https://yashshah138.github.io/Data_Structures1/ct_doc) Reviewed by Daniel T.
[Link to runtime video](https://youtu.be/CTiaXashFsg)

**Comment by JakubPonulak** [comment]
Study plan and PBL plan incorporated, includes specific details and days -1/1
Quiz 1 Corrections (45/50), includes why he got answer wrong and what videos he can watch to improve - 1/1
Quiz 2 Corrections (46/50), also includes reasoning about correct answer and CB videos to improve this topic - 1/1
Create Task
