### ISSUE TITLE
Week 5 Review Ticket-Christopher Hom

### ISSUE THREAD

**Issue by Chom642** [AkhilNandhakumar/Guython#44]
Graded by: Colin Howard
Score 4.5/5

[PBL Plan](https://github.com/AkhilNandhakumar/Guython/issues/35)
[Study Plan](https://github.com/AkhilNandhakumar/Guython/issues/38)
[Test Corrections](https://github.com/Chom642/Data_Structures/blob/main/TPT.md)
[Create Task Code and Runtime](https://scratch.mit.edu/projects/639956612/)

**Comment by KoolKidKai** [comment]
Score /5

- [x] Study plan and reflection
 - good plan, could use some reflection on how the progress and preparation is going.
- [ ] Quiz 1
 - 
- [ ] Quiz 2
- [ ] Create task reviewed by another person
- [ ] review ticket and crossover score
