### ISSUE TITLE
Week 0 Review Ticket - Jakub

### ISSUE THREAD

**Issue by JakubPonulak** [AkhilNandhakumar/Guython#7]
## Graded by Armaan: 2.9/3

**Team:**
- [Project Description](https://github.com/AkhilNandhakumar/Guython#project-description)
- [Project Plans](https://github.com/AkhilNandhakumar/Guython#project-plans)
- [Wireframe for GitHub Pages](https://docs.google.com/drawings/d/1mogokqAFAM5HKk9fLhzz1qdr9THwx2xbRpUxEg_czEs/edit?usp=sharing)
- [Team Roles + Project Owner](https://github.com/AkhilNandhakumar/Guython#contributors)
- [ScrumBoard Started](https://github.com/AkhilNandhakumar/Guython/projects/1)

GH Pages:  https://akhilnandhakumar.github.io/Guython/

**Individual:**

[TPT](https://jakubponulak.github.io/DataStructures/study) | [TT Code & Runtime](https://jakubponulak.github.io/DataStructures/project_doc) | [Create Task Page](https://jakubponulak.github.io/DataStructures/ct_doc)

**Comment by xXAASXx** [comment]
# SCORE: 4.9/5

### 2.0/2.0 Score for Scrum Team GitHub pages (2 points)

- Everything is linked well and organized for the team and I like the idea that they have for this Trimester. 

Web Project: Project Description, Project Plans/Ideas/Wires, Timebox
Team Roles described, Project Owner or Sponsor described, Scrum Board started

### 2.9/3 Score for Individual GitHub pages (3 points)

GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions( See "GitHub pages actions" at the bottom of each TPT page on cspcoders
- No Github Actions for 5.2 but everything else is there and nice.
GitHub page that documents Data Structures project, using code snippets for key learnings, and links to  GitHub for code and Replit for runtime
- Everything looks good and organized 

GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime

- Again I think he did an amazing job on all the individual things besides him missing 5.2 Github Actions
